/**
 * Seed Data for Container Health Verification
 *
 * 这些数据用于验证容器 → 后端 → 前端的数据同步链路
 * 每个 WindowViewer 组件都有对应的测试数据
 *
 * 使用方式：
 * 1. 容器启动时生成种子数据
 * 2. 前端连接后接收并渲染
 * 3. 数据正常显示 = 同步链路正常
 */

// ============================================================
// 种子数据时间戳（用于追踪数据来源）
// ============================================================

const SEED_TIMESTAMP = Date.now();
const SEED_VERSION = '1.0.0';

// ============================================================
// 组件状态种子数据
// ============================================================

/**
 * PDF Reader 种子数据
 */
export const pdfReaderSeedState = {
  documentId: 'seed/sync-test.pdf',
  currentPage: 1,
  totalPages: 3,
  highlights: [
    {
      id: 'seed-highlight-1',
      page: 1,
      color: '#FFEB3B',
      text: 'Sync verification highlight',
      position: { x: 100, y: 200, width: 300, height: 20 },
    },
  ],
  zoom: 1.0,
  ocrStatus: 'completed' as const,
};

/**
 * LaTeX Editor 种子数据
 */
export const latexEditorSeedState = {
  activeFile: 'main.tex',
  content: `\\documentclass{article}
\\title{Sync Test Document}
\\author{Container Health Check}
\\date{${new Date().toISOString().split('T')[0]}}

\\begin{document}
\\maketitle

\\section{Sync Verification}
This document was generated by the container to verify data synchronization.

\\begin{itemize}
  \\item Container → Backend: \\checkmark
  \\item Backend → Frontend: \\checkmark
  \\item Component Rendering: \\checkmark
\\end{itemize}

\\section{Timestamp}
Generated at: ${new Date().toISOString()}

\\end{document}
`,
  cursorPosition: { line: 1, column: 0 },
  compileStatus: 'idle' as const,
  files: [
    { path: 'main.tex', type: 'tex' as const },
    { path: 'references.bib', type: 'bib' as const },
  ],
};

/**
 * Code Playground 种子数据
 */
export const codePlaygroundSeedState = {
  mode: 'script' as const,
  template: 'python',
  selectedFile: 'sync_test.py',
  files: [
    {
      path: 'sync_test.py',
      language: 'python',
      content: `#!/usr/bin/env python3
"""
Container Sync Test Script
Generated at: ${new Date().toISOString()}
"""

import json
from datetime import datetime

def verify_sync():
    """Verify container → frontend sync is working."""
    result = {
        "status": "success",
        "source": "container",
        "timestamp": datetime.now().isoformat(),
        "components": {
            "pdf-reader": True,
            "latex-editor": True,
            "code-playground": True,
            "jupyter-notebook": True,
            "ai-editor": True,
            "ag-grid": True,
            "bento-gallery": True,
            "three-viewer": True,
        }
    }
    return result

if __name__ == "__main__":
    result = verify_sync()
    print(json.dumps(result, indent=2))
`,
    },
  ],
  terminalOutput: `$ python sync_test.py
{
  "status": "success",
  "source": "container",
  "timestamp": "${new Date().toISOString()}",
  "components": {
    "pdf-reader": true,
    "latex-editor": true,
    "code-playground": true,
    "jupyter-notebook": true,
    "ai-editor": true,
    "ag-grid": true,
    "bento-gallery": true,
    "three-viewer": true
  }
}
`,
  buildStatus: 'success' as const,
};

/**
 * Jupyter Notebook 种子数据
 */
export const jupyterNotebookSeedState = {
  activeCellIndex: 0,
  cellCount: 3,
  kernelStatus: 'idle' as const,
  sessionId: `seed-session-${SEED_TIMESTAMP}`,
  executionCount: 3,
  cells: [
    {
      id: 'seed-cell-1',
      type: 'markdown' as const,
      source: `# Container Sync Verification

This notebook verifies the data sync pipeline from container to frontend.

**Generated:** ${new Date().toISOString()}`,
      outputs: [],
      status: 'idle' as const,
    },
    {
      id: 'seed-cell-2',
      type: 'code' as const,
      source: `import pandas as pd
import numpy as np

# Create test data
data = {
    'Component': ['pdf-reader', 'latex-editor', 'code-playground',
                  'jupyter-notebook', 'ai-editor', 'ag-grid',
                  'bento-gallery', 'three-viewer'],
    'Status': ['✓'] * 8,
    'Sync': ['OK'] * 8
}

df = pd.DataFrame(data)
df`,
      outputs: [
        {
          output_type: 'execute_result',
          data: {
            'text/html': `<table border="1">
<tr><th>Component</th><th>Status</th><th>Sync</th></tr>
<tr><td>pdf-reader</td><td>✓</td><td>OK</td></tr>
<tr><td>latex-editor</td><td>✓</td><td>OK</td></tr>
<tr><td>code-playground</td><td>✓</td><td>OK</td></tr>
<tr><td>jupyter-notebook</td><td>✓</td><td>OK</td></tr>
<tr><td>ai-editor</td><td>✓</td><td>OK</td></tr>
<tr><td>ag-grid</td><td>✓</td><td>OK</td></tr>
<tr><td>bento-gallery</td><td>✓</td><td>OK</td></tr>
<tr><td>three-viewer</td><td>✓</td><td>OK</td></tr>
</table>`,
          },
          execution_count: 1,
        },
      ],
      executionCount: 1,
      status: 'idle' as const,
    },
    {
      id: 'seed-cell-3',
      type: 'code' as const,
      source: `# Sync timestamp
print(f"Sync verified at: ${new Date().toISOString()}")`,
      outputs: [
        {
          output_type: 'stream',
          name: 'stdout',
          text: `Sync verified at: ${new Date().toISOString()}\n`,
        },
      ],
      executionCount: 2,
      status: 'idle' as const,
    },
  ],
  variables: [
    { name: 'df', type: 'DataFrame', shape: '(8, 3)', value: '<DataFrame>' },
    { name: 'data', type: 'dict', value: '{...}' },
  ],
};

/**
 * AI Editor 种子数据
 */
export const aiEditorSeedState = {
  content: `# Container Sync Verification

This document was automatically generated by the container to verify the data synchronization pipeline.

## Sync Status

| Component | Status |
|-----------|--------|
| pdf-reader | ✓ Connected |
| latex-editor | ✓ Connected |
| code-playground | ✓ Connected |
| jupyter-notebook | ✓ Connected |
| ai-editor | ✓ Connected |
| ag-grid | ✓ Connected |
| bento-gallery | ✓ Connected |
| three-viewer | ✓ Connected |

## Verification Details

- **Source:** Container
- **Timestamp:** ${new Date().toISOString()}
- **Seed Version:** ${SEED_VERSION}

If you can read this content, the sync pipeline is working correctly.
`,
  documentId: 'seed-doc-sync-test',
  wordCount: 85,
  characterCount: 520,
  lastSavedAt: SEED_TIMESTAMP,
};

/**
 * AG Grid 种子数据
 */
export const agGridSeedState = {
  dataSourceId: 'seed-grid-sync-test',
  rowCount: 8,
  columnDefs: [
    { field: 'component', headerName: 'Component', type: 'string' },
    { field: 'status', headerName: 'Status', type: 'string' },
    { field: 'syncLatency', headerName: 'Sync Latency (ms)', type: 'number' },
    { field: 'lastSync', headerName: 'Last Sync', type: 'date' },
  ],
  selectedRowIds: [],
  filterModel: {},
  sortModel: [{ colId: 'component', sort: 'asc' as const }],
  // 实际行数据（供前端直接渲染）
  rowData: [
    { id: '1', component: 'pdf-reader', status: '✓', syncLatency: 12, lastSync: new Date().toISOString() },
    { id: '2', component: 'latex-editor', status: '✓', syncLatency: 8, lastSync: new Date().toISOString() },
    { id: '3', component: 'code-playground', status: '✓', syncLatency: 15, lastSync: new Date().toISOString() },
    { id: '4', component: 'jupyter-notebook', status: '✓', syncLatency: 22, lastSync: new Date().toISOString() },
    { id: '5', component: 'ai-editor', status: '✓', syncLatency: 5, lastSync: new Date().toISOString() },
    { id: '6', component: 'ag-grid', status: '✓', syncLatency: 3, lastSync: new Date().toISOString() },
    { id: '7', component: 'bento-gallery', status: '✓', syncLatency: 18, lastSync: new Date().toISOString() },
    { id: '8', component: 'three-viewer', status: '✓', syncLatency: 25, lastSync: new Date().toISOString() },
  ],
};

/**
 * Bento Gallery 种子数据
 */
export const bentoGallerySeedState = {
  selectedImageId: 'seed-image-1',
  images: [
    {
      id: 'seed-image-1',
      src: '/assets/seed/sync-test-1.png',
      alt: 'Sync Test Image 1',
      width: 800,
      height: 600,
      caption: 'Container sync verification - Image 1',
    },
    {
      id: 'seed-image-2',
      src: '/assets/seed/sync-test-2.png',
      alt: 'Sync Test Image 2',
      width: 600,
      height: 800,
      caption: 'Container sync verification - Image 2',
    },
    {
      id: 'seed-image-3',
      src: '/assets/seed/sync-test-3.png',
      alt: 'Sync Test Image 3',
      width: 1200,
      height: 400,
      caption: 'Container sync verification - Image 3',
    },
  ],
};

/**
 * Three Viewer 种子数据
 */
export const threeViewerSeedState = {
  modelId: 'seed-model-sync-test',
  cameraPosition: [0, 2, 5],
  modelUrl: '/assets/seed/sync-test-model.glb',
  backgroundColor: '#1a1a2e',
  lightIntensity: 1.0,
  autoRotate: false,
};

// ============================================================
// 完整的组件状态集合
// ============================================================

export function generateSeedComponentStates(): Record<string, unknown> {
  return {
    'pdf-reader': pdfReaderSeedState,
    'latex-editor': latexEditorSeedState,
    'code-playground': codePlaygroundSeedState,
    'jupyter-notebook': jupyterNotebookSeedState,
    'ai-editor': aiEditorSeedState,
    'ag-grid': agGridSeedState,
    'bento-gallery': bentoGallerySeedState,
    'three-viewer': threeViewerSeedState,
  };
}

// ============================================================
// 消息种子数据
// ============================================================

export function generateSeedMessages(): unknown[] {
  const now = new Date().toISOString();
  return [
    {
      id: `seed-msg-${SEED_TIMESTAMP}-1`,
      workspaceId: 'default',
      senderId: 'system',
      senderType: 'agent',
      senderName: 'System',
      content: `🔗 **Container Initialized**\n\nSync pipeline verification data loaded.\n\n- Seed Version: ${SEED_VERSION}\n- Timestamp: ${now}\n- Components: 8 active`,
      contentType: 'markdown',
      timestamp: now,
      metadata: {
        type: 'seed',
        version: SEED_VERSION,
      },
    },
    {
      id: `seed-msg-${SEED_TIMESTAMP}-2`,
      workspaceId: 'default',
      senderId: 'agent-research',
      senderType: 'agent',
      senderName: 'Aria (Research)',
      content: 'Container sync test data ready. All 8 WindowViewer components have been initialized with seed data.',
      contentType: 'text',
      timestamp: new Date(Date.now() + 1000).toISOString(),
    },
  ];
}

// ============================================================
// 任务种子数据
// ============================================================

export function generateSeedTasks(): unknown[] {
  return [
    {
      id: 'seed-task-health-check',
      title: 'Container Health Verification',
      description: 'Verify all components can receive and render seed data from container',
      status: 'completed',
      progress: 100,
      subtasks: [
        { id: 'seed-subtask-1', parentId: 'seed-task-health-check', title: 'PDF Reader initialized', status: 'completed' },
        { id: 'seed-subtask-2', parentId: 'seed-task-health-check', title: 'LaTeX Editor initialized', status: 'completed' },
        { id: 'seed-subtask-3', parentId: 'seed-task-health-check', title: 'Code Playground initialized', status: 'completed' },
        { id: 'seed-subtask-4', parentId: 'seed-task-health-check', title: 'Jupyter Notebook initialized', status: 'completed' },
        { id: 'seed-subtask-5', parentId: 'seed-task-health-check', title: 'AI Editor initialized', status: 'completed' },
        { id: 'seed-subtask-6', parentId: 'seed-task-health-check', title: 'AG Grid initialized', status: 'completed' },
        { id: 'seed-subtask-7', parentId: 'seed-task-health-check', title: 'Bento Gallery initialized', status: 'completed' },
        { id: 'seed-subtask-8', parentId: 'seed-task-health-check', title: 'Three Viewer initialized', status: 'completed' },
      ],
    },
  ];
}

// ============================================================
// 参与者种子数据
// ============================================================

export function generateSeedParticipants(): unknown[] {
  return [
    { id: 'user-1', name: 'Me', type: 'user', status: 'online', role: 'owner' },
    { id: 'system', name: 'System', type: 'agent', status: 'online', role: 'system' },
    { id: 'agent-research', name: 'Aria (Research)', type: 'agent', status: 'online', role: 'agent' },
    { id: 'agent-code', name: 'CodeBot', type: 'agent', status: 'online', role: 'agent' },
    { id: 'agent-writing', name: 'Quill (Writing)', type: 'agent', status: 'online', role: 'agent' },
  ];
}

// ============================================================
// Timeline 种子数据
// ============================================================

export function generateSeedTimeline(): unknown[] {
  const baseTime = SEED_TIMESTAMP;
  return [
    {
      id: `seed-timeline-${baseTime}-1`,
      timestamp: baseTime,
      componentType: 'system',
      action: 'container_started',
      description: 'Container initialized with seed data',
      actorId: 'system',
      actorType: 'agent',
    },
    {
      id: `seed-timeline-${baseTime}-2`,
      timestamp: baseTime + 100,
      componentType: 'pdf-reader',
      action: 'document_loaded',
      description: 'Loaded seed PDF document',
      actorId: 'system',
      actorType: 'agent',
    },
    {
      id: `seed-timeline-${baseTime}-3`,
      timestamp: baseTime + 200,
      componentType: 'code-playground',
      action: 'code_loaded',
      description: 'Loaded sync verification script',
      actorId: 'system',
      actorType: 'agent',
    },
    {
      id: `seed-timeline-${baseTime}-4`,
      timestamp: baseTime + 300,
      componentType: 'jupyter-notebook',
      action: 'notebook_initialized',
      description: 'Created sync verification notebook',
      actorId: 'system',
      actorType: 'agent',
    },
    {
      id: `seed-timeline-${baseTime}-5`,
      timestamp: baseTime + 400,
      componentType: 'ag-grid',
      action: 'data_loaded',
      description: 'Loaded component status table',
      actorId: 'system',
      actorType: 'agent',
    },
  ];
}

// ============================================================
// 完整的会话种子数据
// ============================================================

export interface SeedSessionData {
  messages: unknown[];
  tasks: unknown[];
  participants: unknown[];
  timeline: unknown[];
  componentStates: Record<string, unknown>;
  agentState: {
    status: string;
    currentStep: number;
    totalSteps: number;
  };
  metadata: {
    seedVersion: string;
    generatedAt: string;
    source: string;
  };
}

export function generateSeedSession(): SeedSessionData {
  return {
    messages: generateSeedMessages(),
    tasks: generateSeedTasks(),
    participants: generateSeedParticipants(),
    timeline: generateSeedTimeline(),
    componentStates: generateSeedComponentStates(),
    agentState: {
      status: 'idle',
      currentStep: 0,
      totalSteps: 0,
    },
    metadata: {
      seedVersion: SEED_VERSION,
      generatedAt: new Date().toISOString(),
      source: 'container',
    },
  };
}

// ============================================================
// 导出便捷方法
// ============================================================

export default {
  generateSeedSession,
  generateSeedComponentStates,
  generateSeedMessages,
  generateSeedTasks,
  generateSeedParticipants,
  generateSeedTimeline,
  SEED_VERSION,
};
