blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/LuminPulse-AI/Prismer/discussions
    about: Ask questions, share ideas, and discuss Prismer
  - name: Discord
    url: https://discord.gg/VP2HQHbHGn
    about: Chat with the community in real-time
