/**
 * Agent Artifacts API
 *
 * POST /api/agents/:id/artifacts
 *
 * Saves an artifact (image, PDF, data) generated by the agent to the
 * workspace's collection. Handles S3 upload for binary content and
 * creates an asset record in remote MySQL.
 *
 * Body: { title, type, content (base64 or URL), mimeType? }
 * Response: { success: true, data: { assetId, url } }
 */

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { createLogger } from '@/lib/logger';

const log = createLogger('AgentArtifacts');

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const { id: agentId } = await params;
    const body = await request.json();
    const { title, type, content, mimeType } = body;

    if (!title || !type || !content) {
      return NextResponse.json(
        { success: false, error: 'title, type, and content are required' },
        { status: 400 }
      );
    }

    // Resolve workspace from agent
    const agent = await prisma.agentInstance.findUnique({
      where: { id: agentId },
      select: { workspaceId: true },
    });

    if (!agent?.workspaceId) {
      return NextResponse.json(
        { success: false, error: 'Agent not found or no workspace bound' },
        { status: 404 }
      );
    }

    const workspace = await prisma.workspaceSession.findUnique({
      where: { id: agent.workspaceId },
      select: { settings: true, name: true },
    });

    if (!workspace) {
      return NextResponse.json(
        { success: false, error: 'Workspace not found' },
        { status: 404 }
      );
    }

    const settings = workspace.settings ? JSON.parse(workspace.settings as string) : {};
    let collectionId = settings.collectionId;

    // Ensure collection binding exists
    if (!collectionId) {
      const { workspaceService } = await import('@/lib/services/workspace.service');
      collectionId = await workspaceService.ensureCollectionBinding(agent.workspaceId);
    }

    const { getRemoteUserId } = await import('@/lib/services/workspace.service');
    const userId = getRemoteUserId();

    try {
      const { assetService } = await import('@/lib/services/asset.service');

      // Map artifact type to asset type (AssetType = 'paper' | 'note')
      const assetTypeMap: Record<string, 'paper' | 'note'> = {
        image: 'note',
        pdf: 'paper',
        data: 'note',
        notebook: 'note',
      };

      // Handle base64 content — upload to S3
      let s3Key: string | undefined;
      let assetUrl: string | undefined;

      if (content.startsWith('data:') || content.match(/^[A-Za-z0-9+/=]+$/)) {
        // Base64 content — upload to S3
        const { S3Client, PutObjectCommand } = await import('@aws-sdk/client-s3');
        if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY || !process.env.AWS_S3_BUCKET) {
          return NextResponse.json({ success: false, error: 'S3 not configured' }, { status: 500 });
        }
        const s3Client = new S3Client({
          region: process.env.AWS_REGION || 'us-east-1',
          credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          },
        });

        // Strip data URI prefix if present
        const base64Data = content.includes(',') ? content.split(',')[1] : content;
        const buffer = Buffer.from(base64Data, 'base64');

        const ext = mimeType?.split('/')[1] || type;
        s3Key = `workspace/${agent.workspaceId}/artifacts/${Date.now()}-${title.replace(/\s+/g, '_')}.${ext}`;

        await s3Client.send(new PutObjectCommand({
          Bucket: process.env.AWS_S3_BUCKET!,
          Key: s3Key,
          Body: buffer,
          ContentType: mimeType || 'application/octet-stream',
        }));

        assetUrl = `https://${process.env.AWS_S3_BUCKET!}.s3.${process.env.AWS_REGION || 'us-east-1'}.amazonaws.com/${s3Key}`;
        log.info('Artifact uploaded to S3', { s3Key, size: buffer.length });
      } else {
        // URL content — just reference it
        assetUrl = content;
      }

      // Create asset record
      const asset = await assetService.create({
        userId,
        assetType: assetTypeMap[type] || 'note',
        title,
        source: 'upload' as const,
        pdfS3Key: s3Key,
        metadata: {
          sourceId: `workspace:${agent.workspaceId}`,
          fileName: title,
        },
      });

      // Link to collection if available
      if (collectionId) {
        const { collectionService } = await import('@/lib/services/collection.service');
        await collectionService.addAsset(collectionId, asset.id, userId);
        log.info('Artifact linked to collection', {
          assetId: asset.id,
          collectionId,
        });
      }

      return NextResponse.json({
        success: true,
        data: { assetId: asset.id, url: assetUrl, s3Key },
      });
    } catch (err) {
      log.warn('Remote asset service unavailable', {
        error: err instanceof Error ? err.message : String(err),
      });
      return NextResponse.json({
        success: true,
        data: { assetId: null, warning: 'Remote service unavailable' },
      });
    }
  } catch (error) {
    log.error('Artifact save error', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
