/**
 * Agent Artifacts API
 *
 * POST /api/agents/:id/artifacts
 *
 * Saves an artifact (image, PDF, data) generated by the agent to the
 * workspace's collection. Binary content is stored locally so the
 * self-host build can operate without S3.
 *
 * Body: { title, type, content (base64 or URL), mimeType? }
 * Response: { success: true, data: { assetId, url } }
 */

import { NextRequest, NextResponse } from 'next/server';
import { storeLocalAssetBuffer } from '@/lib/assets/storage';
import prisma from '@/lib/prisma';
import { createLogger } from '@/lib/logger';

const log = createLogger('AgentArtifacts');

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const { id: agentId } = await params;
    const body = await request.json();
    const { title, type, content, mimeType } = body;

    if (!title || !type || !content) {
      return NextResponse.json(
        { success: false, error: 'title, type, and content are required' },
        { status: 400 }
      );
    }

    // Resolve workspace from agent
    const agent = await prisma.agentInstance.findUnique({
      where: { id: agentId },
      select: { workspaceId: true },
    });

    if (!agent?.workspaceId) {
      return NextResponse.json(
        { success: false, error: 'Agent not found or no workspace bound' },
        { status: 404 }
      );
    }

    const workspace = await prisma.workspaceSession.findUnique({
      where: { id: agent.workspaceId },
      select: { settings: true, name: true },
    });

    if (!workspace) {
      return NextResponse.json(
        { success: false, error: 'Workspace not found' },
        { status: 404 }
      );
    }

    const settings = workspace.settings ? JSON.parse(workspace.settings as string) : {};
    let collectionId = settings.collectionId;

    // Ensure collection binding exists
    if (!collectionId) {
      const { workspaceService } = await import('@/lib/services/workspace.service');
      collectionId = await workspaceService.ensureCollectionBinding(agent.workspaceId);
    }

    const { getRemoteUserId } = await import('@/lib/services/workspace.service');
    const userId = getRemoteUserId();

    try {
      const { assetService } = await import('@/lib/services/asset.service');

      // Map artifact type to asset type (AssetType = 'paper' | 'note')
      const assetTypeMap: Record<string, 'paper' | 'note'> = {
        image: 'note',
        pdf: 'paper',
        data: 'note',
        notebook: 'note',
      };

      // Handle binary content by persisting it locally
      let storageKey: string | undefined;
      let assetUrl: string | undefined;
      let fileName: string | undefined;
      let assetMimeType = mimeType || 'application/octet-stream';

      if (content.startsWith('data:') || content.match(/^[A-Za-z0-9+/=]+$/)) {
        // Strip data URI prefix if present
        const base64Data = content.includes(',') ? content.split(',')[1] : content;
        const buffer = Buffer.from(base64Data, 'base64');
        fileName = title.includes('.') ? title : `${title.replace(/\s+/g, '_')}.${type}`;
        const storedFile = await storeLocalAssetBuffer({
          buffer,
          fileName,
          mimeType: assetMimeType,
          workspaceId: agent.workspaceId,
          category: 'artifacts',
        });

        storageKey = storedFile.storageKey;
        fileName = storedFile.fileName;
        assetMimeType = storedFile.mimeType;
        log.info('Artifact stored locally', { storageKey, size: buffer.length });
      } else {
        // URL content — just reference it
        assetUrl = content;
      }

      // Create asset record
      const asset = await assetService.create({
        userId,
        assetType: assetTypeMap[type] || 'note',
        title,
        source: 'upload' as const,
        storageProvider: storageKey ? 'local' : assetUrl ? 'external' : null,
        storageKey,
        externalUrl: assetUrl,
        fileName,
        mimeType: assetMimeType,
        metadata: {
          sourceId: `workspace:${agent.workspaceId}`,
          fileName: fileName || title,
        },
      });

      // Link to collection if available
      if (collectionId) {
        const { collectionService } = await import('@/lib/services/collection.service');
        await collectionService.addAsset(collectionId, asset.id, userId);
        log.info('Artifact linked to collection', {
          assetId: asset.id,
          collectionId,
        });
      }

      return NextResponse.json({
        success: true,
        data: { assetId: asset.id, url: assetUrl || asset.fileUrl, storageKey },
      });
    } catch (err) {
      log.warn('Artifact storage failed', {
        error: err instanceof Error ? err.message : String(err),
      });
      return NextResponse.json({
        success: true,
        data: { assetId: null, warning: 'Local asset persistence failed' },
      });
    }
  } catch (error) {
    log.error('Artifact save error', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
